apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloh-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
