apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: hello-service
  name: hello-service
spec:
  ports:
  - name: http-service
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-world
  type: ClusterIP
