apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: service-test
  name: service-test
spec:
  ports:
  - name: http-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-world
  type: ClusterIP
